# Generated by Django 3.2 on 2023-05-12 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_title_and_author',
        ),
    ]
