# Generated by Django 3.2 on 2023-05-13 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_unique_title_and_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='genretitle',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('name', 'year')},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id', 'username')},
        ),
    ]
